/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as GameInviteCodeImport } from './routes/game_.$inviteCode'
import { Route as AdminPuzzleImport } from './routes/admin/puzzle'
import { Route as AdminGameImport } from './routes/admin/game'
import { Route as AdminPuzzleAddImport } from './routes/admin/puzzle_.add'
import { Route as AdminGameRoomIdImport } from './routes/admin/game_.$roomId'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GameInviteCodeRoute = GameInviteCodeImport.update({
  id: '/game_/$inviteCode',
  path: '/game/$inviteCode',
  getParentRoute: () => rootRoute,
} as any)

const AdminPuzzleRoute = AdminPuzzleImport.update({
  id: '/puzzle',
  path: '/puzzle',
  getParentRoute: () => AdminRoute,
} as any)

const AdminGameRoute = AdminGameImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AdminRoute,
} as any)

const AdminPuzzleAddRoute = AdminPuzzleAddImport.update({
  id: '/puzzle_/add',
  path: '/puzzle/add',
  getParentRoute: () => AdminRoute,
} as any)

const AdminGameRoomIdRoute = AdminGameRoomIdImport.update({
  id: '/game_/$roomId',
  path: '/game/$roomId',
  getParentRoute: () => AdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/admin/game': {
      id: '/admin/game'
      path: '/game'
      fullPath: '/admin/game'
      preLoaderRoute: typeof AdminGameImport
      parentRoute: typeof AdminImport
    }
    '/admin/puzzle': {
      id: '/admin/puzzle'
      path: '/puzzle'
      fullPath: '/admin/puzzle'
      preLoaderRoute: typeof AdminPuzzleImport
      parentRoute: typeof AdminImport
    }
    '/game_/$inviteCode': {
      id: '/game_/$inviteCode'
      path: '/game/$inviteCode'
      fullPath: '/game/$inviteCode'
      preLoaderRoute: typeof GameInviteCodeImport
      parentRoute: typeof rootRoute
    }
    '/admin/game_/$roomId': {
      id: '/admin/game_/$roomId'
      path: '/game/$roomId'
      fullPath: '/admin/game/$roomId'
      preLoaderRoute: typeof AdminGameRoomIdImport
      parentRoute: typeof AdminImport
    }
    '/admin/puzzle_/add': {
      id: '/admin/puzzle_/add'
      path: '/puzzle/add'
      fullPath: '/admin/puzzle/add'
      preLoaderRoute: typeof AdminPuzzleAddImport
      parentRoute: typeof AdminImport
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminGameRoute: typeof AdminGameRoute
  AdminPuzzleRoute: typeof AdminPuzzleRoute
  AdminGameRoomIdRoute: typeof AdminGameRoomIdRoute
  AdminPuzzleAddRoute: typeof AdminPuzzleAddRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGameRoute: AdminGameRoute,
  AdminPuzzleRoute: AdminPuzzleRoute,
  AdminGameRoomIdRoute: AdminGameRoomIdRoute,
  AdminPuzzleAddRoute: AdminPuzzleAddRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/game': typeof AdminGameRoute
  '/admin/puzzle': typeof AdminPuzzleRoute
  '/game/$inviteCode': typeof GameInviteCodeRoute
  '/admin/game/$roomId': typeof AdminGameRoomIdRoute
  '/admin/puzzle/add': typeof AdminPuzzleAddRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/game': typeof AdminGameRoute
  '/admin/puzzle': typeof AdminPuzzleRoute
  '/game/$inviteCode': typeof GameInviteCodeRoute
  '/admin/game/$roomId': typeof AdminGameRoomIdRoute
  '/admin/puzzle/add': typeof AdminPuzzleAddRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/game': typeof AdminGameRoute
  '/admin/puzzle': typeof AdminPuzzleRoute
  '/game_/$inviteCode': typeof GameInviteCodeRoute
  '/admin/game_/$roomId': typeof AdminGameRoomIdRoute
  '/admin/puzzle_/add': typeof AdminPuzzleAddRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/game'
    | '/admin/puzzle'
    | '/game/$inviteCode'
    | '/admin/game/$roomId'
    | '/admin/puzzle/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/game'
    | '/admin/puzzle'
    | '/game/$inviteCode'
    | '/admin/game/$roomId'
    | '/admin/puzzle/add'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/game'
    | '/admin/puzzle'
    | '/game_/$inviteCode'
    | '/admin/game_/$roomId'
    | '/admin/puzzle_/add'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  GameInviteCodeRoute: typeof GameInviteCodeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  GameInviteCodeRoute: GameInviteCodeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/game_/$inviteCode"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/game",
        "/admin/puzzle",
        "/admin/game_/$roomId",
        "/admin/puzzle_/add"
      ]
    },
    "/admin/game": {
      "filePath": "admin/game.tsx",
      "parent": "/admin"
    },
    "/admin/puzzle": {
      "filePath": "admin/puzzle.tsx",
      "parent": "/admin"
    },
    "/game_/$inviteCode": {
      "filePath": "game_.$inviteCode.tsx"
    },
    "/admin/game_/$roomId": {
      "filePath": "admin/game_.$roomId.tsx",
      "parent": "/admin"
    },
    "/admin/puzzle_/add": {
      "filePath": "admin/puzzle_.add.tsx",
      "parent": "/admin"
    }
  }
}
ROUTE_MANIFEST_END */
